import { ArrowRight, ExternalLink, Landmark, ReceiptText } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { requirePermission } from "@/lib/auth/context";
import { bankMovementLabel, bankSourceHref, bankSourceLabel } from "@/lib/bank-account-presentation";
import { formatCurrency } from "@/lib/format";
import { bankAccountService } from "@/lib/services/bankAccountService";
import { timeZoneForCountry } from "@/lib/shop-timezone";

export const dynamic = "force-dynamic";
function dt(value: Date, tz: string) { return new Intl.DateTimeFormat("ar", { year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:tz }).format(value); }
export default async function BankMovementDetailsPage({ params }:{ params:Promise<{id:string}> }) {
  const { id } = await params; const auth = await requirePermission("reports:read"); const movement = await bankAccountService.getMovementById(auth.shop.id,id); if (!movement) notFound();
  const currency=auth.shop.currency||"SAR"; const tz=timeZoneForCountry(auth.shop.countryCode); const href=bankSourceHref(movement);
  return <div className="mx-auto max-w-5xl space-y-6" dir="rtl"><div className="flex flex-wrap items-start justify-between gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><Link href="/bank-accounts" className="inline-flex items-center gap-1 text-xs font-black text-teal-700 hover:underline"><ArrowRight className="h-4 w-4"/>الحسابات البنكية</Link><div className="mt-3 flex items-center gap-2"><h1 className="text-2xl font-black text-slate-950">تفاصيل الحركة البنكية</h1><span className={`rounded-full px-3 py-1 text-[11px] font-black ${movement.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{movement.status==="ACTIVE"?"فعالة":"ملغاة"}</span></div><p className="mt-1 text-sm font-bold text-slate-500">{bankMovementLabel(movement.type)} — {movement.accountName}</p></div>{href?<Button asChild className="rounded-xl"><Link href={href}><ExternalLink className="ml-2 h-4 w-4"/>فتح المصدر</Link></Button>:null}</div>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="المبلغ" value={`${movement.direction==="IN"?"+":"−"} ${formatCurrency(Number(movement.amount),currency)}`}/><Metric label="الرصيد قبل الحركة" value={formatCurrency(Number(movement.balanceBefore),currency)}/><Metric label="الرصيد بعد الحركة" value={formatCurrency(Number(movement.balanceAfter),currency)}/><Metric label="الحساب" value={movement.accountName}/></section>
  <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 bg-slate-50/70 px-5 py-4"><div className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-teal-600"/><h2 className="font-black text-slate-900">بيانات الحركة الكاملة</h2></div></div><dl className="grid sm:grid-cols-2"><Info label="نوع الحركة" value={bankMovementLabel(movement.type)}/><Info label="الاتجاه" value={movement.direction==="IN"?"دخول إلى الحساب":"خروج من الحساب"}/><Info label="المصدر" value={bankSourceLabel(movement.sourceType)}/><Info label="مرجع المصدر" value={movement.sourceReference||"—"}/><Info label="مرجع الحركة" value={movement.reference||"—"}/><Info label="رقم الحركة" value={movement.id}/><Info label="العميل" value={movement.customerName||"—"}/><Info label="هاتف العميل" value={movement.customerPhone||"—"}/><Info label="الطرف المقابل" value={movement.counterpartyName||"—"}/><Info label="نوع الطرف المقابل" value={movement.counterpartyType||"—"}/><Info label="مجموعة التحويل" value={movement.transferGroupId||"—"}/><Info label="نفذها" value={movement.createdByName||"غير معروف"}/><Info label="وقت حدوث الحركة" value={dt(movement.occurredAt,tz)}/><Info label="وقت تسجيلها بالنظام" value={dt(movement.createdAt,tz)}/><Info label="المنطقة الزمنية" value={tz}/><Info label="الحالة" value={movement.status==="ACTIVE"?"فعالة":"ملغاة"}/><Info label="وقت الإلغاء" value={movement.voidedAt?dt(movement.voidedAt,tz):"—"}/><Info label="ألغيت بواسطة" value={movement.voidedByName||"—"}/></dl></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-700"><Landmark className="h-5 w-5"/></span><div><h2 className="font-black text-slate-900">البيان</h2><p className="mt-2 text-sm font-semibold leading-7 text-slate-600">{movement.description||"لا يوجد بيان إضافي."}</p></div></div></section></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-black text-slate-400">{label}</div><div className="mt-2 break-words font-numeric text-lg font-black text-slate-950">{value}</div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="border-b border-slate-100 px-5 py-4 sm:odd:border-l"><dt className="text-xs font-black text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm font-black text-slate-800">{value}</dd></div>}
