import { ArrowRight, Banknote, Boxes, CircleDollarSign, CreditCard, ExternalLink, PackageX, ReceiptText, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { requirePermission } from "@/lib/auth/context";
import { formatCurrency } from "@/lib/format";
import { dailySummaryService } from "@/lib/services/dailySummaryService";

export const dynamic = "force-dynamic";

export default async function DailySummaryPage() {
  const auth = await requirePermission("reports:read");
  const s = await dailySummaryService.getDailySummary(auth.shop.id);
  const currency = auth.shop.currency || "SAR";
  const day = new Intl.DateTimeFormat("ar-EG", { weekday:"long", year:"numeric", month:"long", day:"numeric", timeZone:s.timeZone }).format(new Date());
  return <div className="space-y-7" dir="rtl">
    <PageHeader eyebrow="جرد يومي شامل" title="ملخص اليوم" description={`صورة مالية وتشغيلية كاملة ليوم ${day}. الأرقام اليومية محسوبة حسب توقيت المتجر.`} actions={<div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-xl font-black"><Link href="/dashboard"><ArrowRight className="ml-1.5 h-4 w-4"/>لوحة التحكم</Link></Button><Button asChild className="rounded-xl font-black"><Link href="/reports">التقارير والأرباح</Link></Button></div>} />

    <section><Title title="نتيجة اليوم المالية" text="المبيعات والتكاليف والتحصيل والربح حتى هذه اللحظة."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="إجمالي مبيعات اليوم" value={formatCurrency(s.totals.sales,currency)} helper="كل قنوات البيع المحققة" icon={ReceiptText}/>
      <Metric label="المقبوض فعلياً" value={formatCurrency(s.totals.collected,currency)} helper="كل الأموال المحصلة اليوم" icon={Banknote}/>
      <Metric label="مجمل الربح" value={formatCurrency(s.totals.grossProfit,currency)} helper="بعد التكاليف + عمولات التحويلات" icon={TrendingUp}/>
      <Metric label="مصروفات اليوم" value={formatCurrency(s.totals.expenses,currency)} helper="المصروفات المسجلة اليوم" icon={TrendingDown}/>
      <Metric label="صافي الربح" value={formatCurrency(s.totals.netProfit,currency)} helper="مجمل الربح ناقص المصروفات" icon={CircleDollarSign} featured/>
    </div></section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,0.6fr)]">
      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="text-sm font-black text-slate-900 dark:text-slate-100">المبيعات والربح حسب النشاط</h2><p className="mt-1 text-[11px] font-bold text-slate-400">تكلفة الصيانة تدخل فقط عندما توجد فاتورة غير ملغاة لنفس التذكرة.</p></div><div className="overflow-x-auto"><table className="erp-table min-w-[760px]"><thead><tr><th>النشاط</th><th>العمليات</th><th>المبيعات / الحجم</th><th>التكلفة</th><th>الربح</th><th>تفاصيل</th></tr></thead><tbody>{s.channels.map(c=><tr key={c.key}><td><div className="font-black text-slate-900 dark:text-slate-100">{c.label}</div>{c.volumeOnly?<div className="mt-1 text-[9px] font-bold text-amber-600">الحجم ليس مبيعات؛ الربح هنا هو العمولة فقط.</div>:null}</td><td className="font-numeric font-bold">{c.count}</td><td className="font-numeric font-black">{formatCurrency(c.revenue,currency)}</td><td className="font-numeric font-bold text-rose-700">{c.volumeOnly?"—":formatCurrency(c.cost,currency)}</td><td className={`font-numeric font-black ${c.profit>=0?"text-emerald-700":"text-rose-700"}`}>{formatCurrency(c.profit,currency)}</td><td><Button asChild size="sm" variant="outline" className="rounded-lg"><Link href={c.href}>فتح<ExternalLink className="mr-1 h-3.5 w-3.5"/></Link></Button></td></tr>)}</tbody></table></div></div>
      <div className="space-y-4"><Panel title="التحصيل والمتبقي" icon={CreditCard} rows={[["المقبوض فعلياً اليوم",s.totals.collected],["المتبقي من أعمال اليوم",s.totals.outstandingFromToday],["ربح عمولات المحافظ",s.totals.transferCommissionProfit]]} currency={currency}/><Panel title="السيولة والأرصدة الحالية" icon={WalletCards} rows={[["إجمالي الأموال التشغيلية",s.liquidity.total],["الدرج النقدي",s.liquidity.drawerBalance],["المحافظ الإلكترونية",s.liquidity.wallets.reduce((a,x)=>a+x.balance,0)],["أرصدة مزودي الخدمات",s.liquidity.providers.reduce((a,x)=>a+x.balance,0)]]} currency={currency}/></div>
    </section>

    <section className="grid gap-5 xl:grid-cols-2">
      <Box title="تفصيل الأموال الموجودة الآن" icon={WalletCards} text="هذه أرصدة حالية وليست إيراد اليوم."><div className="mt-4 space-y-2">{s.liquidity.sources.map(x=><Link key={`${x.kind}:${x.id}`} href={x.href} className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 px-3 py-2.5 hover:border-primary/30 hover:bg-primary/5 dark:border-slate-800"><span className="text-xs font-black text-slate-700 dark:text-slate-300">{x.label}</span><span className="font-numeric text-sm font-black">{formatCurrency(x.balance,currency)}</span></Link>)}</div></Box>
      <Box title="المخزون والتوالف" icon={Boxes} text="قيمة المخزون الحالية والتالف المسجل اليوم."><div className="mt-4 grid gap-3 sm:grid-cols-2"><Mini label="قيمة المخزون بسعر التكلفة" value={formatCurrency(s.inventory.valueAtCost,currency)}/><Mini label="قيمة التوالف اليوم" value={formatCurrency(s.inventory.damageValue,currency)} helper={`${s.inventory.damageCount} حركة تالف`}/></div>{s.inventory.damageItems.length?<div className="mt-4 border-t border-slate-100 pt-4 dark:border-slate-800"><p className="mb-2 text-[10px] font-black text-slate-500">المنتجات التي سجل عليها تالف اليوم</p><div className="flex flex-wrap gap-2">{s.inventory.damageItems.map(x=><Button key={x.inventoryItemId} asChild size="sm" variant="outline" className="rounded-lg border-rose-200 text-rose-700"><Link href={`/inventory/${x.inventoryItemId}#inventory-movements`}><PackageX className="ml-1 h-3.5 w-3.5"/>{x.name} ({x.quantity})</Link></Button>)}</div></div>:<p className="mt-4 text-xs font-bold text-slate-400">لا توجد توالف مسجلة اليوم.</p>}</Box>
    </section>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><Title title="الذمم والالتزامات الحالية" text="هذه أرصدة حالية حتى الآن وليست محصورة بما حدث اليوم."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Debt label="إجمالي ديون العملاء" value={s.debts.customerOutstanding} currency={currency} href="/debts" helper="الرصيد الحالي في دفتر الديون"/><Debt label="ديون خارجية / يدوية" value={s.debts.externalOutstanding} currency={currency} href="/debts" helper="أرصدة افتتاحية وديون غير مرتبطة ببيع معروف"/><Debt label="علينا للموردين" value={s.debts.supplierPayable} currency={currency} href="/suppliers" helper={`مشتريات ${formatCurrency(s.debts.supplierPurchaseOutstanding,currency)} + ديون سابقة ${formatCurrency(s.debts.supplierManualOutstanding,currency)}`}/><Debt label="صافي مستحق الموردين" value={s.debts.supplierNetPayable} currency={currency} href="/suppliers" helper={`بعد خصم رصيد لنا لدى الموردين ${formatCurrency(s.debts.supplierCredit,currency)}`}/></div></section>

    {s.electronicCategories.length?<section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><Title title="تفصيل الخدمات الإلكترونية اليوم" text="تفصيل حسب التصنيفات الفعلية التي يستخدمها المتجر."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{s.electronicCategories.map(x=><div key={x.category} className="rounded-2xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex items-center justify-between"><span className="text-xs font-black">{x.category}</span><span className="font-numeric text-[10px] font-bold text-slate-400">{x.count} عملية</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Small label="المبيعات" value={formatCurrency(x.revenue,currency)}/><Small label="التكلفة" value={formatCurrency(x.cost,currency)}/><Small label="الربح" value={formatCurrency(x.profit,currency)}/></div></div>)}</div></section>:null}
  </div>;
}

function Title({title,text}:{title:string;text:string}){return <div className="mb-4"><h2 className="text-sm font-black text-slate-900 dark:text-slate-100">{title}</h2><p className="mt-1 text-[10px] font-bold text-slate-400">{text}</p></div>}
function Metric({label,value,helper,icon:Icon,featured=false}:{label:string;value:string;helper:string;icon:typeof Banknote;featured?:boolean}){return <div className={`rounded-2xl border p-4 shadow-sm ${featured?"border-emerald-300 bg-emerald-50/60 dark:border-emerald-800 dark:bg-emerald-950/20":"border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"}`}><div className="flex justify-between gap-3"><div><p className="text-[10px] font-black text-slate-500">{label}</p><p className="mt-2 font-numeric text-xl font-black">{value}</p><p className="mt-1 text-[9px] font-bold text-slate-400">{helper}</p></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 dark:bg-slate-900"><Icon className="h-4.5 w-4.5"/></span></div></div>}
function Panel({title,icon:Icon,rows,currency}:{title:string;icon:typeof WalletCards;rows:Array<[string,number]>;currency:string}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><Icon className="h-5 w-5 text-primary"/><h3 className="text-sm font-black">{title}</h3></div><div className="mt-4 space-y-2">{rows.map(([l,v])=><div key={l} className="flex justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2.5 dark:bg-slate-900"><span className="text-[11px] font-bold text-slate-500">{l}</span><span className="font-numeric text-sm font-black">{formatCurrency(v,currency)}</span></div>)}</div></div>}
function Box({title,text,icon:Icon,children}:{title:string;text:string;icon:typeof WalletCards;children:React.ReactNode}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40"><Icon className="h-5 w-5"/></span><div><h2 className="text-sm font-black">{title}</h2><p className="mt-1 text-[10px] font-bold text-slate-400">{text}</p></div></div>{children}</div>}
function Mini({label,value,helper}:{label:string;value:string;helper?:string}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[9px] font-black text-slate-400">{label}</p><p className="mt-1 font-numeric text-sm font-black">{value}</p>{helper?<p className="mt-1 text-[9px] font-bold text-slate-400">{helper}</p>:null}</div>}
function Debt({label,value,currency,href,helper}:{label:string;value:number;currency:string;href:string;helper:string}){return <Link href={href} className="rounded-2xl border border-slate-200 p-4 hover:border-primary/40 hover:bg-primary/5 dark:border-slate-800"><p className="text-[10px] font-black text-slate-500">{label}</p><p className="mt-2 font-numeric text-lg font-black">{formatCurrency(value,currency)}</p><p className="mt-1 text-[9px] font-bold leading-5 text-slate-400">{helper}</p></Link>}
function Small({label,value}:{label:string;value:string}){return <div><p className="text-[8px] font-black text-slate-400">{label}</p><p className="mt-1 font-numeric text-[11px] font-black">{value}</p></div>}
