import { ArrowRight, Banknote, Boxes, CheckCircle2, Clock3, PackageCheck, Pencil, ReceiptText, RotateCcw, Scale, Truck } from "lucide-react";
import type { ReactNode } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/page-header";
import { requirePermission } from "@/lib/auth/context";
import { bankAccountService } from "@/lib/services/bankAccountService";
import { formatCurrency } from "@/lib/format";
import { purchaseReceivingService } from "@/lib/services/purchaseReceivingService";
import { ClonePurchaseButton } from "../_clone-purchase-button";
import { PurchaseOperationsPanel } from "../_purchase-operations-panel";

export const dynamic = "force-dynamic";
type PurchaseDetailPageProps = { params: Promise<{ id: string }>; searchParams: Promise<{ posted?: string }> };

export default async function PurchaseDetailPage({ params, searchParams }: PurchaseDetailPageProps) {
  const { id } = await params;
  const query = await searchParams;
  const auth = await requirePermission("inventory:read");
  const canManage = auth.permissions.includes("inventory:manage");
  const invoice = await purchaseReceivingService.getPurchaseInvoice(auth.shop.id, id).catch(() => null);
  if (!invoice) notFound();

  const supplierDisplay = invoice.supplierName ?? invoice.supplierNameSnapshot ?? "مورد نقدي غير مسجل";
  const paymentState = Number(invoice.balanceDue) <= 0.009
    ? "مسواة بالكامل"
    : Number(invoice.amountPaid) > 0 || Number(invoice.returnAdjustmentTotal) > 0
      ? "مسواة جزئياً"
      : "غير مسددة";
  const receiptState = invoice.receiptStatus === "COMPLETE" ? "مستلمة بالكامل" : invoice.receiptStatus === "PARTIAL" ? "مستلمة جزئياً" : "لم تُستلم بعد";
  const itemNameById = new Map(invoice.items.map((item) => [item.id, item.inventoryItemName ?? item.newItemName ?? "صنف"]));

  const [walletRows, bankAccountRows, paymentSources] = canManage && invoice.status === "POSTED"
    ? await Promise.all([
        purchaseReceivingService.listPurchaseFinancialWallets(auth.shop.id),
        bankAccountService.listAccounts(auth.shop.id),
        purchaseReceivingService.listPaymentSources(auth.shop.id),
      ])
    : [[], [], []];

  return <div className="space-y-6">
    <PageHeader
      eyebrow="المخزون • فاتورة شراء"
      title={invoice.status === "DRAFT" ? "مسودة فاتورة شراء" : "تفاصيل فاتورة الشراء والاستلام"}
      description={invoice.supplierInvoiceNumber ? `فاتورة المورد: ${invoice.supplierInvoiceNumber}` : "فاتورة شراء بدون رقم مورد"}
      actions={<div className="flex flex-wrap items-start gap-2"><Button asChild variant="outline"><Link href="/inventory/purchases"><ArrowRight className="ml-1.5 h-4 w-4" />القائمة</Link></Button>{invoice.status === "DRAFT" && canManage && <Button asChild><Link href={`/inventory/purchases/new?draft=${invoice.id}`}><Pencil className="ml-1.5 h-4 w-4" />متابعة المسودة</Link></Button>}{canManage && <ClonePurchaseButton purchaseId={invoice.id} />}</div>}
    />

    {query.posted && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-black text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200"><CheckCircle2 className="ml-2 inline h-4 w-4" />{query.posted === "partial" ? "تم اعتماد الفاتورة وتسجيل الكميات المستلمة فقط. الباقي ينتظر استلاماً لاحقاً." : "تم اعتماد الفاتورة واستلام كل الكميات."}</div>}
    {invoice.status === "POSTED" && <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs font-semibold leading-6 text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">الفاتورة الأصلية بعد الاعتماد لا تُعاد كتابتها ولا تُحذف آثارها. أي استلام لاحق أو دفعة أو مرتجع أو تسوية يُسجل كسجل مستقل مرتبط بها، لذلك تبقى حالة الاستلام منفصلة عن حالة السداد.</div>}

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <InfoCard icon={Truck} label="المورد" value={supplierDisplay} helper={invoice.supplierId ? "مورد مسجل" : "شراء نقدي غير مسجل"} />
      <InfoCard icon={ReceiptText} label="رقم فاتورة المورد" value={invoice.supplierInvoiceNumber ?? "غير مسجل"} helper={new Intl.DateTimeFormat("ar", { dateStyle: "long" }).format(invoice.invoiceDate)} />
      <InfoCard icon={Banknote} label="الإجمالي" value={formatCurrency(Number(invoice.total), invoice.currency)} helper={paymentState} />
      <InfoCard icon={PackageCheck} label="حالة الاستلام" value={receiptState} helper={`${invoice.items.reduce((sum, item) => sum + item.receivedQuantity, 0)} من ${invoice.items.reduce((sum, item) => sum + item.orderedQuantity, 0)} وحدة مسجلة`} />
      <InfoCard icon={Clock3} label="الحالة" value={invoice.status === "POSTED" ? "معتمدة" : "مسودة"} helper={invoice.postedAt ? `اعتمدت ${new Intl.DateTimeFormat("ar", { dateStyle: "medium", timeStyle: "short" }).format(invoice.postedAt)}` : "لا أثر مخزني أو مالي بعد"} />
    </section>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="font-black text-slate-900 dark:text-slate-100">بنود الفاتورة</h2><p className="mt-1 text-xs font-semibold text-slate-400">كمية الفاتورة منفصلة عن المستلم والمتبقي والمرتجع. تكلفة كل حركة تحفظ كلقطة وقت العملية.</p></div>
      <div className="hidden overflow-x-auto md:block"><table className="erp-table min-w-[1150px]"><thead><tr><th>الصنف</th><th>الباركود / SKU</th><th>الفاتورة</th><th>المستلم</th><th>المتبقي</th><th>المرتجع</th><th>تكلفة الوحدة</th><th>الإجمالي</th><th>حركات المخزون</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id}><td className="font-black text-slate-900 dark:text-slate-100">{item.inventoryItemName ?? item.newItemName ?? "—"}</td><td className="font-numeric text-slate-500"><div>{item.inventoryItemBarcode ?? item.newItemBarcode ?? "بدون باركود"}</div><div className="mt-1 text-[10px] text-slate-400">{item.inventoryItemSku ?? item.newItemSku ?? "بدون SKU"}</div></td><td className="font-numeric font-bold">{item.orderedQuantity}</td><td className="font-numeric font-black text-emerald-700 dark:text-emerald-300">{item.receivedQuantity}</td><td className="font-numeric font-black text-amber-700 dark:text-amber-300">{item.remainingQuantity}</td><td className="font-numeric font-black text-rose-700 dark:text-rose-300">{item.returnedQuantity}</td><td className="font-numeric">{formatCurrency(Number(item.unitCost), invoice.currency)}</td><td className="font-numeric font-black">{formatCurrency(Number(item.lineTotal), invoice.currency)}</td><td>{item.movements.length ? item.movements.map((movement) => <div key={movement.id} className={`text-[10px] font-semibold ${movement.quantityChange >= 0 ? "text-emerald-600" : "text-rose-600"}`}>{movement.quantityChange > 0 ? "+" : ""}{movement.quantityChange} → رصيد {movement.quantityAfter ?? "—"}</div>) : <span className="text-xs text-slate-400">لا توجد حركة</span>}</td></tr>)}</tbody></table></div>
      <div className="divide-y divide-slate-100 md:hidden dark:divide-slate-800">{invoice.items.map((item) => <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-black text-slate-900 dark:text-slate-100">{item.inventoryItemName ?? item.newItemName ?? "—"}</div><div className="mt-1 text-xs text-slate-400">{item.inventoryItemBarcode ?? item.newItemBarcode ? `باركود: ${item.inventoryItemBarcode ?? item.newItemBarcode}` : "بدون باركود"} • {item.inventoryItemSku ?? item.newItemSku ?? "بدون SKU"}</div></div><span className="rounded-full bg-emerald-50 px-2 py-1 font-numeric text-[10px] font-black text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{item.receivedQuantity}/{item.orderedQuantity}</span></div><div className="mt-3 grid grid-cols-4 gap-2 rounded-xl bg-slate-50 p-3 text-center dark:bg-slate-950/50"><Mini label="المستلم" value={String(item.receivedQuantity)} /><Mini label="المتبقي" value={String(item.remainingQuantity)} /><Mini label="المرتجع" value={String(item.returnedQuantity)} /><Mini label="قابل للإرجاع الآن" value={String(item.returnableQuantity)} /></div><div className="mt-2 grid grid-cols-2 gap-2"><Mini label="تكلفة الوحدة" value={formatCurrency(Number(item.unitCost), invoice.currency)} /><Mini label="إجمالي السطر" value={formatCurrency(Number(item.lineTotal), invoice.currency)} /></div>{item.movements.length > 0 && <div className="mt-2 space-y-1">{item.movements.map((movement) => <div key={movement.id} className={`text-[10px] font-bold ${movement.quantityChange >= 0 ? "text-emerald-700 dark:text-emerald-300" : "text-rose-700 dark:text-rose-300"}`}><Boxes className="ml-1 inline h-3 w-3" />{movement.quantityChange > 0 ? "+" : ""}{movement.quantityChange}، الرصيد بعد الحركة {movement.quantityAfter ?? "—"}</div>)}</div>}{item.updateSalePrice && <div className="mt-2 rounded-lg bg-indigo-50 px-2 py-1.5 text-[10px] font-bold text-indigo-700 dark:bg-indigo-950/30 dark:text-indigo-200">تم اختيار تحديث سعر البيع صراحةً ضمن هذه الفاتورة{item.salePriceBeforeSnapshot ? ` من ${formatCurrency(Number(item.salePriceBeforeSnapshot), invoice.currency)}` : ""}.</div>}{item.importedPurchaseUnit && <div className="mt-2 text-[10px] font-semibold text-slate-400">وحدة الشراء في المصدر: {item.importedPurchaseUnit}</div>}</article>)}</div>
    </section>

    <section className="grid gap-5 xl:grid-cols-2">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black text-slate-900 dark:text-slate-100">الإجماليات والمستحق</h2><div className="mt-4 space-y-2 text-sm"><Row label="مجموع البنود" value={formatCurrency(Number(invoice.subtotal), invoice.currency)} /><Row label="الخصم" value={formatCurrency(Number(invoice.discountTotal), invoice.currency)} /><Row label="الشحن / المصاريف الإضافية" value={formatCurrency(Number(invoice.extraCostsTotal), invoice.currency)} /><div className="border-t border-slate-100 pt-2 dark:border-slate-800"><Row label="إجمالي الفاتورة الأصلي" value={formatCurrency(Number(invoice.total), invoice.currency)} strong /><Row label="دفعات فعلية" value={formatCurrency(Number(invoice.amountPaid), invoice.currency)} /><Row label="خصم مرتجعات من المستحق" value={formatCurrency(Number(invoice.returnAdjustmentTotal), invoice.currency)} /><Row label="المتبقي لهذه الفاتورة" value={formatCurrency(Number(invoice.balanceDue), invoice.currency)} strong /></div></div><p className="mt-4 text-[11px] font-semibold leading-5 text-slate-400">تأخر الاستلام لا يخفض المستحق. لا يوجد في بنية مسار الحالية دفتر أستاذ عام/حساب «بضاعة بالطريق»؛ لذلك قيمة غير المستلم تظهر ككمية معلقة على الفاتورة، بينما المخزون الفعلي لا يزيد إلا عند الاستلام.</p></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black text-slate-900 dark:text-slate-100">وضع المورد</h2><div className="mt-4 space-y-2"><Row label="إجمالي المستحق المفتوح لهذا المورد" value={formatCurrency(Number(invoice.supplierOutstanding), invoice.currency)} strong /><Row label="رصيد مرتجعات محفوظ لدى المورد" value={formatCurrency(Number(invoice.supplierCredit), invoice.currency)} /><Row label="صافي عرضي" value={formatCurrency(Number(invoice.supplierOutstanding) - Number(invoice.supplierCredit), invoice.currency)} /></div><p className="mt-3 text-[10px] font-semibold leading-5 text-slate-400">المستحق مشتق من فواتير الشراء المعتمدة المفتوحة، وليس من حقل رصيد منفصل على المورد. رصيد المرتجعات يُعرض مستقلاً حتى لا يغيّر فاتورة بعينها دون اختيارك.</p></div>
    </section>

    <section className="grid gap-5 xl:grid-cols-2">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black text-slate-900 dark:text-slate-100">الدفعات</h2>{invoice.payments.length === 0 ? <Empty>لا توجد دفعة مسجلة على هذه الفاتورة.</Empty> : <div className="mt-4 space-y-3">{invoice.payments.map((payment) => <div key={payment.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black text-slate-700 dark:text-slate-200">{paymentMethodLabel(payment.method)}</span><span className="font-numeric text-sm font-black text-emerald-700 dark:text-emerald-300">{formatCurrency(Number(payment.amount), invoice.currency)}</span></div><div className="mt-1 text-[10px] font-semibold text-slate-400">{payment.sourceName || accountLabel(payment.accountType)}{payment.reference ? ` • مرجع ${payment.reference}` : ""} • {new Intl.DateTimeFormat("ar", { dateStyle: "medium", timeStyle: "short" }).format(payment.paidAt)}{payment.createdByName ? ` • بواسطة ${payment.createdByName}` : ""}</div></div>)}</div>}<div className={`mt-4 rounded-xl border p-4 text-sm font-black ${Number(invoice.balanceDue) > 0 ? "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200" : "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200"}`}>{Number(invoice.balanceDue) > 0 ? `مستحق على الفاتورة: ${formatCurrency(Number(invoice.balanceDue), invoice.currency)}` : "لا يوجد رصيد مستحق لهذه الفاتورة."}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-black text-slate-900 dark:text-slate-100">سجل الاستلام</h2>{invoice.receipts.length === 0 ? <Empty>لا يوجد استلام مسجل حتى الآن.</Empty> : <div className="mt-4 space-y-3">{invoice.receipts.map((receipt) => <div key={receipt.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black text-slate-700 dark:text-slate-200">{new Intl.DateTimeFormat("ar", { dateStyle: "medium", timeStyle: "short" }).format(receipt.receivedAt)}</span><span className="text-[10px] font-bold text-slate-400">{receipt.createdByName ? `بواسطة ${receipt.createdByName}` : ""}</span></div><div className="mt-2 space-y-1">{receipt.lines.map((line) => <div key={`${receipt.id}:${line.purchaseItemId}`} className="flex items-center justify-between gap-3 text-[10px] font-semibold text-slate-500"><span>{itemNameById.get(line.purchaseItemId) ?? "صنف"}</span><span className="font-numeric font-black text-emerald-700 dark:text-emerald-300">+{line.quantity}</span></div>)}</div>{(receipt.reference || receipt.note) && <div className="mt-2 text-[10px] font-semibold text-slate-400">{receipt.reference ? `مرجع ${receipt.reference}` : ""}{receipt.reference && receipt.note ? " • " : ""}{receipt.note}</div>}</div>)}</div>}</div>
    </section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><RotateCcw className="h-4 w-4 text-rose-600" /><h2 className="font-black text-slate-900 dark:text-slate-100">مرتجعات المورد وتسوياتها</h2></div>{invoice.supplierReturns.length === 0 ? <Empty>لا توجد مرتجعات على هذه الفاتورة.</Empty> : <div className="mt-4 space-y-4">{invoice.supplierReturns.map((supplierReturn) => <article key={supplierReturn.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black text-slate-800 dark:text-slate-100">{supplierReturn.reason}</div><div className="mt-1 text-[10px] font-semibold text-slate-400">{new Intl.DateTimeFormat("ar", { dateStyle: "medium", timeStyle: "short" }).format(supplierReturn.returnedAt)}{supplierReturn.createdByName ? ` • بواسطة ${supplierReturn.createdByName}` : ""}{supplierReturn.reference ? ` • مرجع ${supplierReturn.reference}` : ""}</div></div><div className="text-left"><div className="font-numeric text-sm font-black text-rose-700 dark:text-rose-300">{formatCurrency(Number(supplierReturn.totalValue), invoice.currency)}</div><div className="text-[10px] font-bold text-slate-400">غير مسوى {formatCurrency(Number(supplierReturn.remainingSettlementValue), invoice.currency)}</div></div></div><div className="mt-3 grid gap-1 sm:grid-cols-2">{supplierReturn.lines.map((line) => <div key={`${supplierReturn.id}:${line.purchaseItemId}`} className="flex items-center justify-between rounded-lg bg-slate-50 px-2 py-1.5 text-[10px] font-semibold dark:bg-slate-950/50"><span>{itemNameById.get(line.purchaseItemId) ?? "صنف"}</span><span className="font-numeric font-black">-{line.quantity} • {formatCurrency(Number(line.lineTotal), invoice.currency)}</span></div>)}</div>{supplierReturn.settlements.length > 0 && <div className="mt-3 border-t border-slate-100 pt-3 dark:border-slate-800"><div className="mb-2 flex items-center gap-1 text-[10px] font-black text-slate-500"><Scale className="h-3 w-3" />التسويات</div><div className="space-y-1">{supplierReturn.settlements.map((settlement) => <div key={settlement.id} className="flex flex-wrap items-center justify-between gap-2 text-[10px] font-semibold text-slate-500"><span>{settlementLabel(settlement.type)}{settlement.sourceName ? ` • ${settlement.sourceName}` : ""}{settlement.createdByName ? ` • ${settlement.createdByName}` : ""}</span><span className="font-numeric font-black text-slate-800 dark:text-slate-100">{formatCurrency(Number(settlement.amount), invoice.currency)}</span></div>)}</div></div>}</article>)}</div>}</section>

    {invoice.status === "POSTED" && canManage && <PurchaseOperationsPanel
      purchaseId={invoice.id}
      currency={invoice.currency}
      balanceDue={invoice.balanceDue.toString()}
      items={invoice.items.map((item) => ({ id: item.id, name: item.inventoryItemName ?? item.newItemName ?? "صنف", orderedQuantity: item.orderedQuantity, receivedQuantity: item.receivedQuantity, returnedQuantity: item.returnedQuantity, remainingQuantity: item.remainingQuantity, returnableQuantity: item.returnableQuantity, unitCost: item.unitCost.toString() }))}
      supplierReturns={invoice.supplierReturns.map((item) => ({ id: item.id, reason: item.reason, totalValue: item.totalValue.toString(), remainingSettlementValue: item.remainingSettlementValue.toString(), returnedAt: item.returnedAt.toISOString() }))}
      wallets={walletRows.map((wallet) => ({ id: wallet.id, name: wallet.name, currentBalance: wallet.currentBalance.toString() }))}
      bankAccounts={bankAccountRows.map((account) => ({ id: account.id, name: account.name, bankName: account.bankName, currentBalance: account.currentBalance.toString() }))}
      paymentSources={paymentSources}
    />}

    {invoice.notes && <section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm font-semibold leading-7 text-slate-600 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300"><h2 className="mb-2 font-black text-slate-900 dark:text-slate-100">ملاحظات</h2>{invoice.notes}</section>}
  </div>;
}

function InfoCard({ icon: Icon, label, value, helper }: { icon: typeof Truck; label: string; value: string; helper: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><Icon className="h-4.5 w-4.5" /></span><div className="min-w-0"><div className="text-[10px] font-bold text-slate-400">{label}</div><div className="truncate text-sm font-black text-slate-900 dark:text-slate-100">{value}</div></div></div><div className="mt-3 text-[10px] font-semibold text-slate-400">{helper}</div></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div><div className="text-[9px] font-bold text-slate-400">{label}</div><div className="mt-1 truncate font-numeric text-[10px] font-black text-slate-700 dark:text-slate-200">{value}</div></div>; }
function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex items-center justify-between gap-4 ${strong ? "font-black text-slate-900 dark:text-slate-100" : "font-semibold text-slate-600 dark:text-slate-300"}`}><span>{label}</span><span className="font-numeric">{value}</span></div>; }
function Empty({ children }: { children: ReactNode }) { return <div className="mt-4 rounded-xl bg-slate-50 p-5 text-center text-xs font-semibold text-slate-400 dark:bg-slate-950/40">{children}</div>; }
function paymentMethodLabel(method: string) { if (method === "CASH") return "نقدي"; if (method === "CARD") return "بطاقة"; if (method === "BANK_TRANSFER") return "تحويل بنكي"; return "أخرى"; }
function accountLabel(account: string | null) { if (account === "DRAWER") return "الدرج النقدي"; if (account === "WALLET") return "محفظة مالية"; if (account === "OTHER") return "مصدر خارجي"; return "مصدر غير محدد"; }
function settlementLabel(type: string) { if (type === "PAYABLE_REDUCTION") return "خصم من المستحق"; if (type === "SUPPLIER_CREDIT") return "رصيد لدى المورد"; return "مبلغ مسترد"; }
