import { AlertTriangle, ArrowRightLeft, Banknote, Boxes, CheckCircle2, CircleDollarSign, Clock, Code2, Crown, FileText, Plus, Receipt, ShoppingCart, Sparkles, TrendingDown, TrendingUp, Wrench } from "lucide-react";
import { SubscriptionStatus } from "@prisma/client";
import Image from "next/image";
import Link from "next/link";
import { DatabaseUnavailable } from "@/components/database-unavailable";
import { Button } from "@/components/ui/button";
import { DashboardActivityCard, DashboardActivityItem, DashboardAttentionCard, DashboardEmptyActivity, DashboardQuickAction, DashboardSection, DashboardStatCard, type DashboardTone } from "@/components/dashboard/masar-dashboard-ui";
import { MasarJourney } from "@/components/dashboard/masar-journey";
import { MasarWaveBackground } from "@/components/dashboard/masar-wave-background";
import { DomainAnnouncement } from "@/components/dashboard/domain-announcement";
import { ActivationChecklist } from "@/components/onboarding/activation-checklist";
import { ContextualFeatureDiscovery } from "@/components/onboarding/contextual-feature-discovery";
import { MonetizationPrompt } from "@/components/onboarding/monetization-prompt";
import { getCurrentShopContext } from "@/lib/current-shop";
import { isDatabaseConnectionError } from "@/lib/database-errors";
import { formatCurrency, formatDate } from "@/lib/format";
import { dailySummaryService } from "@/lib/services/dailySummaryService";
import { dashboardService } from "@/lib/services/dashboardService";
import { subscriptionService, type SubscriptionOverview } from "@/lib/services/subscriptionService";

export const dynamic = "force-dynamic";
type Stat = { label:string; helper:string; value:string|number; icon:typeof Wrench; href:string; tone:DashboardTone };

export default async function DashboardPage() {
  let metrics: Awaited<ReturnType<typeof dashboardService.getDashboardMetrics>>;
  let activity: Awaited<ReturnType<typeof dashboardService.getRecentActivity>>;
  let shopContext: Awaited<ReturnType<typeof getCurrentShopContext>>;
  let subscriptionOverview: SubscriptionOverview | null = null;
  let dailySummary: Awaited<ReturnType<typeof dailySummaryService.getDailySummaryHeadline>> | null = null;
  try {
    shopContext = await getCurrentShopContext(); const { shopId } = shopContext; const canReadReports = shopContext.permissions.includes("reports:read");
    [metrics,activity,subscriptionOverview,dailySummary] = await Promise.all([
      dashboardService.getDashboardMetrics(shopId), dashboardService.getRecentActivity(shopId),
      shopContext.membershipRole === "OWNER" ? subscriptionService.getSubscriptionOverview(shopId).catch(()=>null) : Promise.resolve(null),
      canReadReports ? dailySummaryService.getDailySummaryHeadline(shopId).catch(()=>null) : Promise.resolve(null),
    ]);
  } catch (error) { if (isDatabaseConnectionError(error)) return <DatabaseUnavailable/>; throw error; }

  const currency=shopContext.currency||"SAR"; const todayStr=new Intl.DateTimeFormat("ar-EG",{weekday:"long",year:"numeric",month:"long",day:"numeric",timeZone:shopContext.timeZone}).format(new Date());
  const financialCards: Stat[] = dailySummary ? [
    {label:"إجمالي مبيعات اليوم",helper:"كل قنوات البيع المحققة اليوم",value:formatCurrency(dailySummary.totals.sales,currency),icon:ShoppingCart,href:"/daily-summary",tone:"brand"},
    {label:"المقبوض فعلياً اليوم",helper:"الأموال التي تم تحصيلها فعلياً",value:formatCurrency(dailySummary.totals.collected,currency),icon:Banknote,href:"/daily-summary",tone:"success"},
    {label:"مجمل ربح اليوم",helper:"بعد التكاليف + عمولات التحويلات",value:formatCurrency(dailySummary.totals.grossProfit,currency),icon:TrendingUp,href:"/daily-summary",tone:dailySummary.totals.grossProfit>=0?"info":"danger"},
    {label:"مصروفات اليوم",helper:"كل المصروفات المسجلة اليوم",value:formatCurrency(dailySummary.totals.expenses,currency),icon:TrendingDown,href:"/daily-summary",tone:"warning"},
    {label:"صافي ربح اليوم",helper:"مجمل الربح بعد خصم المصروفات",value:formatCurrency(dailySummary.totals.netProfit,currency),icon:CircleDollarSign,href:"/daily-summary",tone:dailySummary.totals.netProfit>=0?"success":"danger"},
  ]:[];
  const statusCards: Stat[] = [
    {label:"طلبات صيانة مفتوحة",helper:"أجهزة قيد العمل بالورشة",value:metrics.openRepairOrdersCount,icon:Wrench,href:"/repair-orders",tone:"brand"},
    {label:"جاهزة للتسليم",helper:"تم إنجازها وبانتظار العميل",value:metrics.readyForDeliveryCount,icon:CheckCircle2,href:"/repair-orders",tone:"success"},
    {label:"طلبات استلمت اليوم",helper:"تذاكر صيانة جديدة مسجلة",value:metrics.repairOrdersCreatedToday,icon:Plus,href:"/repair-orders",tone:"info"},
    {label:"طلبات سلمت اليوم",helper:"أجهزة استلمها أصحابها",value:metrics.deliveredToday,icon:CheckCircle2,href:"/repair-orders",tone:"support"},
    {label:"تنبيهات المخزون",helper:"قطع قاربت على النفاد",value:metrics.lowStockItemsCount,icon:Boxes,href:"/inventory?lowStockOnly=true",tone:"danger"},
  ];
  const hasAttention=metrics.readyForDeliveryCount>0||metrics.lowStockItemsCount>0||metrics.unpaidInvoicesCount>0;

  return <div className="masar-page">
    <DomainAnnouncement/><ActivationChecklist/><ContextualFeatureDiscovery shopId={shopContext.shopId} membershipRole={shopContext.membershipRole}/><MonetizationPrompt/>
    {subscriptionOverview?.effectiveStatus===SubscriptionStatus.TRIALING?<section className="masar-surface-brand flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-teal-600 to-cyan-600 text-white shadow-md"><Crown className="h-5 w-5"/></span><div><p className="text-[17px] font-black text-slate-900">تجربتك الاحترافية فعّالة</p><p className="mt-1 text-[14px] font-semibold text-slate-600">بقي {subscriptionOverview.remainingDays} يوم و{subscriptionOverview.remainingHours} ساعة — جميع مزايا مسار متاحة لك الآن.</p></div></div><Button asChild variant="outline" className="h-10 rounded-xl border-teal-200 bg-white px-4 text-[14px] font-black text-teal-700"><Link href="/support">التواصل مع الدعم</Link></Button></section>:null}
    <section className="relative overflow-hidden rounded-[26px] border border-teal-100/80 bg-gradient-to-br from-teal-50 via-white to-cyan-50/70 p-5 shadow-[0_22px_70px_-46px_rgba(13,148,136,0.52)] sm:p-7"><MasarWaveBackground/><div className="relative flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap items-center gap-2 text-[14px] font-semibold text-slate-500"><span className="masar-badge masar-badge-brand"><Sparkles className="h-3.5 w-3.5"/>{shopContext.shopName}</span><span>أهلاً بك، <strong className="font-black text-slate-700">{shopContext.userName}</strong></span><span className="inline-flex items-center gap-1.5 font-numeric text-slate-400"><Clock className="h-3.5 w-3.5"/>{todayStr}</span></div><div className="flex flex-wrap gap-2.5"><Link href="/repair-orders/new" className="masar-btn-primary"><Plus className="h-4.5 w-4.5"/>طلب صيانة جديد</Link><Link href="/sales/new" className="masar-btn-secondary"><ShoppingCart className="h-4.5 w-4.5"/>عملية بيع POS جديدة</Link></div></div><div className="relative mt-6 text-center"><div className="mx-auto flex justify-center"><Image src="/masar-logo.png" alt="مسار" width={220} height={198} priority className="h-24 w-auto object-contain drop-shadow-sm transition-transform duration-300 hover:scale-105 sm:h-28"/></div><p className="mt-2 text-[16px] font-black text-teal-700">رحلة الجهاز من الاستلام حتى التسليم</p></div><MasarJourney/><p className="relative mt-5 text-center text-[14px] font-semibold text-slate-400">من أول خطوة... حتى يعود الجهاز لصاحبه</p></section>
    <section className="dashboard-pos-launch-wrap" aria-label="اختصار نقطة البيع"><Link href="/point-of-sale" className="dashboard-pos-launch-card"><span className="dashboard-pos-launch-card__content"><span className="dashboard-pos-launch-card__icon"><ShoppingCart className="h-6 w-6"/></span><span className="dashboard-pos-launch-card__copy"><span className="dashboard-pos-launch-card__eyebrow"><Sparkles className="h-3.5 w-3.5"/> مركز العمليات اليومية</span><strong>نقطة البيع</strong><span>بيع مباشر، صيانة، سوفتوير، خدمات إلكترونية ومحافظ — من مكان واحد.</span></span><span className="dashboard-pos-launch-card__action">فتح نقطة البيع<ArrowRightLeft className="h-4 w-4"/></span></span></Link></section>
    {dailySummary?<section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="masar-section-title">ملخص اليوم المالي</h2><p className="masar-section-description">أهم أرقام اليوم المالية في مكان واحد، مع صفحة جرد كاملة للتفاصيل.</p></div><Button asChild variant="outline" className="h-10 rounded-xl border-teal-200 bg-white px-4 text-[12px] font-black text-teal-700"><Link href="/daily-summary">عرض الجرد اليومي الكامل<ArrowRightLeft className="mr-1.5 h-4 w-4"/></Link></Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{financialCards.map(c=><DashboardStatCard key={c.label} {...c}/>)}</div></section>:null}
    <section><div className="mb-4"><h2 className="masar-section-title">حالة الورشة الآن</h2><p className="masar-section-description">الطلبات والتسليمات والمخزون التي تحتاج متابعة تشغيلية.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{statusCards.map(c=><DashboardStatCard key={c.label} {...c}/>)}</div></section>
    {hasAttention?<DashboardSection title="يحتاج انتباهك اليوم" description="حالات تستحق المتابعة قبل نهاية يوم العمل." icon={AlertTriangle}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{metrics.readyForDeliveryCount>0?<DashboardAttentionCard title="أجهزة جاهزة للتسليم" tone="success" href="/repair-orders" action="عرض الأجهزة الجاهزة" description={<>يوجد <strong className="font-numeric font-black text-slate-900">{metrics.readyForDeliveryCount}</strong> جهاز مكتمل الصيانة بانتظار التسليم.</>}/>:null}{metrics.lowStockItemsCount>0?<DashboardAttentionCard title="نقص في المخزون" tone="danger" href="/inventory?lowStockOnly=true" action="مراجعة المخزون" description={<>يوجد <strong className="font-numeric font-black text-slate-900">{metrics.lowStockItemsCount}</strong> قطع بلغت أو تخطت حد إعادة الطلب.</>}/>:null}{metrics.unpaidInvoicesCount>0?<DashboardAttentionCard title="مستحقات غير محصلة" tone="warning" href="/invoices" action="متابعة التحصيل" description={<>توجد <strong className="font-numeric font-black text-slate-900">{metrics.unpaidInvoicesCount}</strong> فواتير معلقة بإجمالي <strong className="font-numeric font-black text-slate-900">{formatCurrency(metrics.unpaidBalanceTotal,currency)}</strong>.</>}/>:null}</div></DashboardSection>:null}
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3"><DashboardActivityCard title="آخر تذاكر صيانة" icon={Wrench}>{activity.repairOrders.length===0?<DashboardEmptyActivity href="/repair-orders/new" label="طلب صيانة جديد"/>:activity.repairOrders.map(x=><DashboardActivityItem key={x.id} href={`/repair-orders/${x.id}`} title={x.ticketNumber} description={`${x.customer?.name??"عميل سريع"} - ${x.deviceBrand??""} ${x.deviceModel??""}`} meta={formatDate(x.createdAt,shopContext.timeZone)}/>)}</DashboardActivityCard><DashboardActivityCard title="آخر عمليات البيع" icon={ShoppingCart}>{activity.sales.length===0?<DashboardEmptyActivity href="/sales/new" label="عملية بيع جديدة"/>:activity.sales.map(x=><DashboardActivityItem key={x.id} href={`/sales/${x.id}`} title={x.receiptNumber??"إيصال بيع"} description={`${x.customer?.name??"عميل نقدي"} - إجمالي: ${formatCurrency(x.total,currency)}`} meta={formatDate(x.soldAt,shopContext.timeZone)}/>)}</DashboardActivityCard><DashboardActivityCard title="آخر الفواتير" icon={FileText}>{activity.invoices.length===0?<DashboardEmptyActivity href="/invoices" label="عرض الفواتير"/>:activity.invoices.map(x=><DashboardActivityItem key={x.id} href={`/invoices/${x.id}`} title={x.invoiceNumber} description={`${x.customer?.name??"عميل سريع"} - متبقي: ${formatCurrency(x.balanceDue,currency)}`} meta={formatDate(x.issuedAt,shopContext.timeZone)}/>)}</DashboardActivityCard></div><DashboardSection title="إجراءات سريعة" description="أكثر العمليات استخداماً في يوم العمل." icon={ArrowRightLeft} className="h-fit xl:sticky xl:top-24"><div className="space-y-2.5"><DashboardQuickAction href="/repair-orders/new" title="فتح تذكرة صيانة" description="تسجيل واستلام جهاز جديد" icon={Wrench} tone="brand"/><DashboardQuickAction href="/sales/new" title="تسجيل عملية POS" description="بيع مباشر لقطع وإكسسوارات" icon={ShoppingCart} tone="warning"/><DashboardQuickAction href="/software-services/new" title="بيع خدمة سوفتوير" description="تفليش، تحديث وخدمات رقمية" icon={Code2} tone="support"/><DashboardQuickAction href="/inventory/new" title="إضافة للمستودع" description="إدخال صنف أو قطعة جديدة" icon={Boxes} tone="info"/><DashboardQuickAction href="/invoices" title="مراجعة المقبوضات" description="متابعة الفواتير المعلقة" icon={Receipt} tone="danger"/><DashboardQuickAction href="/customers" title="سجل العملاء" description="مراجعة حسابات وبيانات العملاء" icon={CheckCircle2} tone="neutral"/></div></DashboardSection></section>
  </div>;
}
